config/routes.rb
Rails.application.routes.draw do
  root "pages#splash_screen"
  resources :categories, only: [:index, :show, :new, :create] do
    resources :operations, only: [:new, :create]
  end
  devise_for :users, path: '', path_names: { sign_in: 'login' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :operation_categories, dependent: :destroy
  has_many :operations, through: :operation_categories

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :operation_categories, dependent: :destroy
  has_many :categories, through: :operation_categories

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/operation_category.rb
class OperationCategory < ApplicationRecord
  belongs_to :operation
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :operations, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:splash_screen]

  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def after_sign_out_path_for(_resource_or_scope)
    root_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @page_title = 'Home'
    @categories = Category.where(user: current_user).all
  end

  def show
    @page_title = 'Transactions'
    @category = Category.find(params[:id])
    @operations = @category.operations
  end

  def new
    @page_title = 'New category'
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  def new
    @page_title = 'New transaction'
    @operation = Operation.new
  end

  def create
    @category = Category.find(params[:operation][:category_id])
    @operation = Operation.new(operation_params)
    @operation.author = current_user

    @operation_category = OperationCategory.new
    @operation_category.category = @category
    @operation_category.operation = @operation
    @operation_category.save

    if @operation.save
      redirect_to category_path(@category), notice: 'Operation was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def operation_params
    params.require(:operation).permit(:name, :amount)
  end

  def category_params
    params.require(:category).permit(:id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def splash_screen
    return unless user_signed_in?

    redirect_to categories_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<section id="categories">
  <% if @categories.any? %>
    <% @categories.each do |category| %>
      <%= link_to category do %>
        <div class="category-box">
          <img src="<%= category.icon %>" alt="<%= category.name %>">
          <div class="info-cont">
            <p class="info"><%= category.name %></p>
            <p class="info"><%= category.updated_at.strftime('%d %b %Y') %></p>
          </div>
          <p class="total"><%= category.operations.sum(:amount) %></p>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <p>Oh no its empty</p>
  <% end %>

</section>

<%= render "shared/big_btn", path: new_category_path, text: "Add category" %>

app/views/categories/new.html.erb
<%= form_with(model: @category) do |f| %>
  <% if @category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-cont">
    <div class="field">
      <%= f.text_field :name, placeholder: "Name", required: true %>
    </div>

    <div class="field">
      <%= f.text_field :icon, placeholder: "Icon url", required: true %>
    </div>
  </div>

  <div>
    <%= f.submit "Save", class: "btn" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<section id="transactions">
  <% if @operations.any? %>
    <div class="total-box">
      <p class="info">Total</p>
      <p class="total"><%= @operations.sum(:amount) %></p>
    </div>

    <% @operations.each do |operation| %>
      <div class="transaction-box">
        <p class="info"><%= operation.updated_at.strftime('%d %b %Y') %></p>
        <p class="info"><%= operation.name %></p>
        <p class="total"><%= operation.amount %></p>
      </div>
    <% end %>
  <% else %>
    <p>Oh no its empty</p>
  <% end %>
</section>

<%= render "shared/big_btn", path: new_category_operation_path(@category), text: "Add transaction" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if controller_name == "categories" || controller_name == "operations" %>
      <header data-controller="menu">
        <nav>
          <% if controller_name == 'categories' && action_name == 'index' %>
            <button type="button" data-action="click->menu#toggleSideMenu">
              <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M4 6H20M4 12H20M4 18H20" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
            </button>
          <% else %>
            <%= link_to categories_path do %>
              <svg viewBox="0 -6.5 36 36" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g id="icons" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"> <g id="ui-gambling-website-lined-icnos-casinoshunter" transform="translate(-342.000000, -159.000000)" fill="#ffffff" fill-rule="nonzero"> <g id="square-filled" transform="translate(50.000000, 120.000000)"> <path d="M317.108012,39.2902857 L327.649804,49.7417043 L327.708994,49.7959169 C327.889141,49.9745543 327.986143,50.2044182 328,50.4382227 L328,50.5617773 C327.986143,50.7955818 327.889141,51.0254457 327.708994,51.2040831 L327.6571,51.2479803 L317.108012,61.7097143 C316.717694,62.0967619 316.084865,62.0967619 315.694547,61.7097143 C315.30423,61.3226668 315.30423,60.6951387 315.694547,60.3080911 L324.702666,51.3738496 L292.99947,51.3746291 C292.447478,51.3746291 292,50.9308997 292,50.3835318 C292,49.8361639 292.447478,49.3924345 292.99947,49.3924345 L324.46779,49.3916551 L315.694547,40.6919089 C315.30423,40.3048613 315.30423,39.6773332 315.694547,39.2902857 C316.084865,38.9032381 316.717694,38.9032381 317.108012,39.2902857 Z M327.115357,50.382693 L316.401279,61.0089027 L327.002151,50.5002046 L327.002252,50.4963719 L326.943142,50.442585 L326.882737,50.382693 L327.115357,50.382693 Z" id="left-arrow" transform="translate(310.000000, 50.500000) scale(-1, 1) translate(-310.000000, -50.500000) "> </path> </g> </g> </g> </g></svg>
            <% end %> 
          <% end %>

          <h1><%= @page_title || "Budget App" %></h1>

          <% unless controller_name == "categories" && action_name == "show" %>
            <button type="button">
              <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M15.7955 15.8111L21 21M18 10.5C18 14.6421 14.6421 18 10.5 18C6.35786 18 3 14.6421 3 10.5C3 6.35786 6.35786 3 10.5 3C14.6421 3 18 6.35786 18 10.5Z" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
            </button>
          <% else %>
            <button type="button"></button>
          <% end %>
        </nav>

        <div class="side-menu" data-menu-target="sidemenu">
          <button type="button" data-action="click->menu#toggleSideMenu">
            <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M10.0303 8.96965C9.73741 8.67676 9.26253 8.67676 8.96964 8.96965C8.67675 9.26255 8.67675 9.73742 8.96964 10.0303L10.9393 12L8.96966 13.9697C8.67677 14.2625 8.67677 14.7374 8.96966 15.0303C9.26255 15.3232 9.73743 15.3232 10.0303 15.0303L12 13.0607L13.9696 15.0303C14.2625 15.3232 14.7374 15.3232 15.0303 15.0303C15.3232 14.7374 15.3232 14.2625 15.0303 13.9696L13.0606 12L15.0303 10.0303C15.3232 9.73744 15.3232 9.26257 15.0303 8.96968C14.7374 8.67678 14.2625 8.67678 13.9696 8.96968L12 10.9393L10.0303 8.96965Z" fill="#ffffff"></path> <path fill-rule="evenodd" clip-rule="evenodd" d="M12 1.25C6.06294 1.25 1.25 6.06294 1.25 12C1.25 17.9371 6.06294 22.75 12 22.75C17.9371 22.75 22.75 17.9371 22.75 12C22.75 6.06294 17.9371 1.25 12 1.25ZM2.75 12C2.75 6.89137 6.89137 2.75 12 2.75C17.1086 2.75 21.25 6.89137 21.25 12C21.25 17.1086 17.1086 21.25 12 21.25C6.89137 21.25 2.75 17.1086 2.75 12Z" fill="#ffffff"></path> </g></svg>
          </button>

          <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
            <div class="nav-link">
              <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" transform="matrix(-1, 0, 0, 1, 0, 0)"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M10 12H20M20 12L17 9M20 12L17 15" stroke="#ffffff" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M4 12C4 7.58172 7.58172 4 12 4M12 20C9.47362 20 7.22075 18.8289 5.75463 17" stroke="#ffffff" stroke-width="1.5" stroke-linecap="round"></path> </g></svg>
              <p class="headline-text">Sign out</p>
            </div>
          <% end %>      
        </div>
      </header>
    <% end %>

    <main>
      <p class="notice"><%= notice %></p>
      <%= yield %>
      <p class="alert"><%= alert %></p>
    </main>
  </body>
</html>

app/views/operations/new.html.erb
<%= form_with(model: @operation, url: category_operations_path(params[:category_id])) do |f| %>
  <% if @operation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% @operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-cont">
    <div class="field">
      <%= f.text_field :name, placeholder: "Name", required: true %>
    </div>

    <div class="field">
      <%= f.number_field :amount, min: 0.01, placeholder: "Amount", step: "any", required: true %>
    </div>

    <div class="field">
      <%= f.collection_select :category_id, Category.where(user: current_user).all, :id, :name, { selected: params[:category_id] } %>
    </div>
  </div>

  <div>
    <%= f.submit "Save", class: "btn" %>
  </div>
<% end %>

app/views/pages/splash_screen.html.erb
<section id="splash-screen">
  <div class="splash-logo">
    <img src="https://www.coolgenerator.com/Data/Textdesign/202308/b5afa0d52a907e6af667d4791a89d487.png" alt="Budget App Logo">
  </div>
  <div class="splash-buttons">
    <%= link_to 'Log In', new_user_session_path, class: "login-btn" %>
    <%= link_to 'Sign Up', new_user_registration_path, class: "signup-btn" %>
  </div>
</section>

app/views/shared/_big_btn.html.erb
<%= link_to path, class: "big-btn" do %>
  <div>
    <p class="headline-text"><%= text %></p>
  </div>
<% end %>